### ISSUE TITLE
Support for playing sound files

### ISSUE THREAD

**Issue by mgrojo** [onox/canberra-ada#3]
It would be nice to be able to play sound files. This is how it would be done in C:

`ca_context_play(ca_gtk_context_get(), 0, CA_PROP_MEDIA_FILENAME, path, NULL);`

**Comment by mgrojo** [comment]
I've implemented this myself. It was not difficult after all. I can make a pull request, but I have a doubt about the "media.role" property. I've added it like in the Event case, but I have the same problem in both: setting Role to Music plays the passed event id or file, but if I pass Event, no sound is played. Is that a problem of my system (Ubuntu Linux 18.04) or is it how it is supposed to behave?

**Comment by onox** [comment]
In both cases the sound should be played. If you set Role to Music then it shows up in pavucontrol. With Role set to Event it won't show up but can still be heard.

**Comment by onox** [comment]
how does the modified package spec of your patch look like?

**Comment by mgrojo** [comment]
I added a Play_File procedure:
```ada
   procedure Play_File
     (Object      : in out Context;
      Filename    : String;
      Event_Sound : out Sound;
      Kind        : Role   := Event;
      Name        : String := "")
```
I'll make the pull-request in a second so you can take it, if you want.

**Comment by onox** [comment]
API looks ok. Does the body re-use the same code as the `Play` procedure? The only thing that is different is that "event.id" is replaced with "media.filename". So it's best if the `Play` and `Play_File` call some private procedure.

**Comment by mgrojo** [comment]
> In both cases the sound should be played. If you set Role to Music then it shows up in pavucontrol. With Role set to Event it won't show up but can still be heard.

I see now. It turned out that effects on my system were almost silenced. It can be heard now as `Event`.
